//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotacaoBcB.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CotacaoBcB.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Cotacoes&gt;
        ///&lt;Cotacao&gt;&lt;Codigo&gt;1&lt;/Codigo&gt;&lt;Descricao&gt;Taxa de câmbio - Livre - Dólar americano (venda) - diário&lt;/Descricao&gt;&lt;/Cotacao&gt;
        ///&lt;Cotacao&gt;&lt;Codigo&gt;3&lt;/Codigo&gt;&lt;Descricao&gt;Taxa de câmbio - Flutuante - Dólar turismo - Venda&lt;/Descricao&gt;&lt;/Cotacao&gt;
        ///&lt;Cotacao&gt;&lt;Codigo&gt;4&lt;/Codigo&gt;&lt;Descricao&gt;Ouro BMF - grama&lt;/Descricao&gt;&lt;/Cotacao&gt;
        ///&lt;Cotacao&gt;&lt;Codigo&gt;5&lt;/Codigo&gt;&lt;Descricao&gt;Ouro Londres - onça troy&lt;/Descricao&gt;&lt;/Cotacao&gt;
        ///&lt;Cotacao&gt;&lt;Codigo&gt;7&lt;/Codigo&gt;&lt;Descricao&gt;Bovespa - í­ndice&lt;/Descricao&gt;&lt;/Cotacao&gt;
        ///&lt;Cotacao&gt;&lt;Codigo&gt;8&lt;/Codigo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string codigosCotacao {
            get {
                return ResourceManager.GetString("codigosCotacao", resourceCulture);
            }
        }
    }
}
